version: 2
jobs:
    build:
        docker:
            - image: node:6
        working_directory: ~/app
        steps:
            - checkout
            - restore_cache:
                key: wts-{{ .Branch }}-{{ checksum "package.json" }}
            - run:
                name: Install Dependencies
                command: yarn install
            - run:
                name: Build
                command: npm run build
            - save_cache:
                key: wts-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "~/.cache/yarn"
            - add_ssh_keys
            - deploy:
                name: Deploy to branch
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        ./.circleci/deploy.sh
                    fi
            - deploy:
                name: Trigger Deploy
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        curl --user ${CIRCLE_API_TOKEN_FOR_DEPLOY}: \
                            --data build_parameters[CIRCLE_JOB]=build \
                            https://circleci.com/api/v1.1/project/github/mark86092/goodjob-deploy-ci/tree/www-stage-old
                    fi
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
